-- AlterEnum
ALTER TYPE "ShopItemKind" ADD VALUE 'RAM_UPGRADE';
ALTER TYPE "ShopItemKind" ADD VALUE 'CPU_UPGRADE';
ALTER TYPE "ShopItemKind" ADD VALUE 'DISK_UPGRADE';
ALTER TYPE "ShopItemKind" ADD VALUE 'BACKUP_SLOT_UPGRADE';

-- AlterTable
ALTER TABLE "ShopItem" ADD COLUMN     "maxTotal" INTEGER;
